/* Generate.c - Generates a given number of random values and stores them
 *  in the files small_test.txt, medium_test.txt, and large_test.txt
 * DO NOT MODIFY THIS FILE. When I test your program I will use the same 
 *  files generated by this program.
 *
 * Format of *_test.txt files are:
 * N
 * #1 #2 ... #N
 *
 * Compile and execute this program by:
 * >> gcc -o gen.ex generate.c
 * >> ./gen.ex
 */

#include <stdio.h>
#include <stdlib.h>

#define N_SMALL  100       // Amount of random numbers to generate for small test case
#define N_MEDIUM 100000    // Amount of random numbers to generate for medium test case
#define N_LARGE  10000000  // Amount of random numbers to generate for large test case

#define MAX 10000     // Max random number value

int main()
{
  FILE *fp_small   = fopen("small_test.txt", "w+");
  FILE *fp_medium  = fopen("medium_test.txt", "w+");
  FILE *fp_large   = fopen("large_test.txt", "w+");
  int i;

  // --- SMALL TEST ---
  fprintf(fp_small, "%i\n", N_SMALL);     // Print total amount of numbers
  for(i = 0; i < N_SMALL; i++)    
    fprintf(fp_small, "%i ", rand()%MAX); // Print N random numbers

  // --- MEDIUM TEST ---
  fprintf(fp_medium, "%i\n", N_MEDIUM);    // Print total amount of numbers
  for(i = 0; i < N_MEDIUM; i++)    
    fprintf(fp_medium, "%i ", rand()%MAX); // Print N random numbers

  // --- LARGE TEST ---
  fprintf(fp_large, "%i\n", N_LARGE);     // Print total amount of numbers
  for(i = 0; i < N_LARGE; i++)    
    fprintf(fp_large, "%i ", rand()%MAX); // Print N random numbers
  
  fclose(fp_small);
  fclose(fp_medium);
  fclose(fp_large);
}
